export const ADD_NEW_TODO = 'ADD_NEW_TODO';
export const DELETE_A_TODO = 'DELETE_A_TODO';
export const EDIT_A_TODO = 'EDIT_A_TODO';
export const UPDATE_A_TODO = 'UPDATE_A_TODO';
export const COMPLETE_A_TODO = 'COMPLETE_A_TODO';
export const CLEAR_ALL_COMPLETED_TODO = 'CLEAR_ALL_COMPLETED_TODO';
export const SET_PRIORITY = 'SET_PRIORITY';
export const SAVED_INTO_LOCALSTORAGE = 'SAVED_INTO_LOCALSTORAGE';
